<a href="https://colab.research.google.com/github/dinapraveen/DATA-ANALYSIS-PROJECT-CLG/blob/main/my_final_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

CITY AIR _QUALITY ANALYSIS DATA SET

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv("/content/cities_air_quality_water_pollution.18-10-2021 (1).csv")

In [ ]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
df.head(3)

,City,"""Region""","""Country""","""AirQuality""","""WaterPollution"""
0,New York City,"""New York""","""United States of America""",46.816038,49.504950
1,"Washington, D.C.","""District of Columbia""","""United States of America""",66.129032,49.107143
2,San Francisco,"""California""","""United States of America""",60.514019,43.000000

In [ ]:
df.tail(3)#prints last few

,City,"""Region""","""Country""","""AirQuality""","""WaterPollution"""
3960,Vic,"""Catalonia""","""Spain""",100.0,0.0
3961,Segovia,"""Castile and Leon""","""Spain""",100.0,0.0
3962,Zamora city,"""Castile and Leon""","""Spain""",100.0,50.0

In [ ]:
df.columns

Index(['City', ' "Region"', ' "Country"', ' "AirQuality"',
       ' "WaterPollution"'],
      dtype='object')

In [ ]:
df.shape

(3963, 5)

In [ ]:
df.dtypes

City                  object
 "Region"             object
 "Country"            object
 "AirQuality"        float64
 "WaterPollution"    float64
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3963 entries, 0 to 3962
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   City               3963 non-null   object
 1    "Region"          3963 non-null   object
 2    "Country"         3963 non-null   object
 3    "AirQuality"      3963 non-null   float64
 4    "WaterPollution"  3963 non-null   float64
dtypes: float64(2), object(3)
memory usage: 185.8+ KB

In [ ]:
df.nunique()

City                 3796
 "Region"            1153
 "Country"            177
 "AirQuality"         667
 "WaterPollution"     561
dtype: int64

DATA SET CLEANING

In [ ]:
df.isnull()

       City   "Region"   "Country"   "AirQuality"   "WaterPollution"
0     False      False       False          False              False
1     False      False       False          False              False
2     False      False       False          False              False
3     False      False       False          False              False
4     False      False       False          False              False
...     ...        ...         ...            ...                ...
3958  False      False       False          False              False
3959  False      False       False          False              False
3960  False      False       False          False              False
3961  False      False       False          False              False
3962  False      False       False          False              False

[3963 rows x 5 columns]

In [ ]:
missing_values = df.isnull().sum()
print("missing values:\n",missing_values)
df.fillna(df.mean(), inplace=True)

missing values:
 City                 0
 "Region"            0
 "Country"           0
 "AirQuality"        0
 "WaterPollution"    0
dtype: int64

<ipython-input-19-dbfcff9f63c5>:3: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.fillna(df.mean(), inplace=True)

REMOVING DUPLICATES

In [ ]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
3958    False
3959    False
3960    False
3961    False
3962    False
Length: 3963, dtype: bool

In [ ]:
df = df.drop_duplicates()

In [ ]:
df.shape

(3963, 5)

DATA MANIPULATING

In [ ]:
df.colums = {'City', "Region", "Country", 'Airquality', 'Waterpollution'}
df.columns

Index(['City', ' "Region"', ' "Country"', ' "AirQuality"',
       ' "WaterPollution"'],
      dtype='object')

In [ ]:
df.isnull().sum()

City                 0
 "Region"            0
 "Country"           0
 "AirQuality"        0
 "WaterPollution"    0
dtype: int64

In [ ]:
df['City']=df['City'].str.strip(' "')
df["Region"] = df["Region"].str.strip(' "')
df["Country"]=df["Country"].str.strip(' "')

KeyError: 'Region'